Add JOB benchmark dataset (imdb dataset)
apache/datafusion pull request #12497
Opened 2024-09-17 05:54 UTC by doupache

## Which issue does this PR close?
Partial Closes https://github.com/apache/datafusion/issues/12311

## Rationale for this change
Add imdb dataset for the JOB benchmarking

## What changes are included in this PR?
Download the the dataset and convert it to parquet files.

## Are these changes tested?
Just like running to generate tpch dataset:
`./bench.sh data tpch`

run:
`./bench.sh data imdb`

## Are there any user-facing changes?
no

2024-09-17 06:21 UTC, doupache commented
Unlike TPCH, which uses table-named folders with partitioned parquet files, IMDB has smaller tables (largest is 360MB). 
We can convert each IMDB table to a single, non-partitioned parquet file.

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/281a2d21-a254-4caf-ae82-5de616a80f4b">

2024-09-17 08:48 UTC, austin362667 commented
Thanks @doupache for paving the way! Got few nit suggestion.
1. Do we prefer benchmark name as `imdb` or `job`?
2. Cloud you add `[1/N]` in the beginning of the PR title to help us track the follow-ups progress?

2024-09-17 09:48 UTC, austin362667 approved these changes

2024-09-17 10:12 UTC, doupache commented
Thanks @austin362667 for the suggestions. **IMDB** is more suitable than **JOB** as it's specific and avoids confusion. **Job** can be used in many different contexts.

Adding 'progress' to the title is also a good idea 👍

2024-09-19 07:55 UTC, austin362667 requested changes

2024-09-19 07:55 UTC, austin362667 commented on benchmarks/src/imdb/convert.rs
> +                .take(schema.fields.len() - 1)
Why takes all columns except the last one?

```suggestion
                .take(schema.fields.len())
```

2024-09-19 19:29 UTC, alamb commented
Thanks @doupache  -- I started the CI jobs, and I will try and test this out manually locally over the next few days

2024-09-20 03:35 UTC, doupache commented
Thanks @austin362667  and @alamb. 

I have updated the PR and learned some Cargo tips from @austin362667. 
Using debug build during development is much faster.


```sh 
#1
cd benchmarks && cargo build 

#2 
cargo run --bin imdb -- convert --input ./data/imdb/ --output ./data/imdb/ --format parquet
```


i also test all 21 parquet  like follwoing.

```sql 
# create table 
CREATE EXTERNAL TABLE name (
    id INTEGER NOT NULL PRIMARY KEY,
    name STRING NOT NULL,
    imdb_index STRING,
    imdb_id INTEGER,
    gender STRING,
    name_pcode_cf STRING,
    name_pcode_nf STRING,
    surname_pcode STRING,
    md5sum STRING
)
STORED AS PARQUET
LOCATION '../benchmarks/data/imdb/temp/name.parquet';

# read 
SELECT * FROM name LIMIT 5;
```

2024-09-20 14:11 UTC, austin362667 commented
> Unlike TPCH, which uses table-named folders with partitioned parquet files, IMDB has smaller tables (largest is 360MB).
We can convert each IMDB table to a single, non-partitioned parquet file.

Sure! I think maybe it's because historical reasons that `ParquetExec` didn't support parallel execution for single Parquet file back then. Now it's being supported in https://github.com/apache/datafusion/pull/5057

2024-09-24 00:34 UTC, austin362667 approved these changes
Thanks @doupache for the contribution and @alamb for the review~
I'll 1. add `imdb` help text. and fix what @andygrove told in PR [2/N] https://github.com/apache/datafusion/pull/1252,
2. non-neg id use UInt32
3 use single context.

2024-09-24 00:55 UTC, merged

2024-09-24 00:55 UTC, alamb commented
Let's keep improving things in the next PR. Thanks @austin362667